Repository yooyouny/logistics-management-service, pull requests merged in 2024-09, with the labels that each got.

#6 [#5] 허브간이동엔티티
  service/gateway/src/main/resources/application.yml
  service/hub/src/main/java/com/sparta/hub/application/dto/interhub/InterHubCreateRequest.java
  service/hub/src/main/java/com/sparta/hub/application/dto/interhub/InterHubResponse.java
  service/hub/src/main/java/com/sparta/hub/application/mapper/InterHubMapper.java
  service/hub/src/main/java/com/sparta/hub/application/service/InterHubService.java
  service/hub/src/main/java/com/sparta/hub/domain/Hub.java
  service/hub/src/main/java/com/sparta/hub/domain/InterHub.java
  service/hub/src/main/java/com/sparta/hub/infrastructure/repository/interhub/InterHubRepository.java
  service/hub/src/main/java/com/sparta/hub/presentation/InterHubController.java
Labels: ✨ Feature

#7 [#4] 사용자 도메인 개발 및 구조 세팅
  common/domain/.gitignore
  common/domain/build.gradle
  common/domain/gradle/wrapper/gradle-wrapper.jar
  common/domain/gradle/wrapper/gradle-wrapper.properties
  common/domain/src/main/java/com/sparta/commons/domain/jpa/BaseEntity.java
  common/domain/src/main/java/com/sparta/commons/domain/jpa/JpaConfig.java
  common/domain/src/main/java/com/sparta/commons/domain/response/FailedResponseBody.java
  common/domain/src/main/java/com/sparta/commons/domain/response/ResponseBody.java
  common/domain/src/main/java/com/sparta/commons/domain/response/SuccessResponseBody.java
  common/domain/src/test/java/com/sparta/commons/domain/DomainApplicationTests.java
  service/user/build.gradle
  service/user/docker-compose.yml
  service/user/src/main/java/com/sparta/user/application/service/UserService.java
  service/user/src/main/java/com/sparta/user/domain/model/ShippingManager.java
  service/user/src/main/java/com/sparta/user/domain/model/User.java
  service/user/src/main/java/com/sparta/user/domain/model/vo/ShippingManagerType.java
  service/user/src/main/java/com/sparta/user/domain/model/vo/UserRole.java
  service/user/src/main/java/com/sparta/user/domain/repository/UserRepository.java
  service/user/src/main/java/com/sparta/user/domain/service/UserDomainService.java
  service/user/src/main/java/com/sparta/user/presentation/controller/UserController.java
  service/user/src/main/resources/application.properties
  service/user/src/main/resources/application.yml
  settings.gradle
Labels: ⚙️ Setting, ✨ Feature

#10 [#1] 주문 관련 엔티티 구현
  common/domain/build.gradle
  common/domain/src/main/java/com/sparta/commons/domain/jpa/BaseEntity.java
  service/order/build.gradle
  service/order/gradle/wrapper/gradle-wrapper.jar
  service/order/gradle/wrapper/gradle-wrapper.properties
  service/order/settings.gradle
  service/order/src/main/java/com/sparta/order/OrderApplication.java
  service/order/src/main/java/com/sparta/order/domain/model/Delivery.java
  service/order/src/main/java/com/sparta/order/domain/model/DeliveryRoute.java
  service/order/src/main/java/com/sparta/order/domain/model/Money.java
  service/order/src/main/java/com/sparta/order/domain/model/Order.java
  service/order/src/main/java/com/sparta/order/domain/model/OrderDetail.java
  service/order/src/main/java/com/sparta/order/domain/model/State.java
  service/order/src/main/resources/application-local.yml
  service/order/src/main/resources/application.properties
  service/order/src/test/java/com/sparta/order/OrderApplicationTests.java
Labels: ⚙️ Setting, ✨ Feature

#12 [#8] 공통 모듈 적용
  common/domain/build.gradle
  service/hub/.env
  service/hub/build.gradle
  service/hub/src/main/java/com/sparta/hub/HubApplication.java
  service/hub/src/main/java/com/sparta/hub/application/dto/hub/HubCreateRequest.java
  service/hub/src/main/java/com/sparta/hub/application/mapper/HubMapper.java
  service/hub/src/main/java/com/sparta/hub/application/mapper/InterHubMapper.java
  service/hub/src/main/java/com/sparta/hub/application/service/HubService.java
  service/hub/src/main/java/com/sparta/hub/domain/Hub.java
  service/hub/src/main/java/com/sparta/hub/domain/InterHub.java
  service/hub/src/main/java/com/sparta/hub/exception/ErrorCode.java
  service/hub/src/main/java/com/sparta/hub/exception/GlobalExceptionHandler.java
  service/hub/src/main/java/com/sparta/hub/infrastructure/repository/hub/HubRepository.java
  service/hub/src/main/java/com/sparta/hub/presentation/HubController.java
  service/hub/src/main/java/com/sparta/hub/presentation/InterHubController.java
  service/hub/src/main/java/com/sparta/hub/presentation/dto/ResponseDto.java
Labels: ✨ Feature

#15 [#11] 주문생성 API 구현
  service/order/order_server/build.gradle
  service/order/order_server/gradlew
  service/order/order_server/gradlew.bat
  service/order/order_server/src/main/java/com/sparta/order/OrderApplication.java
  service/order/order_server/src/main/java/com/sparta/order/application/service/OrderFacadeService.java
  service/order/order_server/src/main/java/com/sparta/order/application/service/OrderService.java
  service/order/order_server/src/main/java/com/sparta/order/domain/model/Delivery.java
  service/order/order_server/src/main/java/com/sparta/order/domain/model/DeliveryRoute.java
  service/order/order_server/src/main/java/com/sparta/order/domain/model/Money.java
  service/order/order_server/src/main/java/com/sparta/order/domain/model/Order.java
  service/order/order_server/src/main/java/com/sparta/order/domain/model/OrderDetail.java
  service/order/order_server/src/main/java/com/sparta/order/domain/model/State.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/repository/OrderDetailRepository.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/repository/OrderRepository.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/controller/OrderController.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/request/OrderCreateRequest.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/request/OrderDetailRequest.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/response/OrderDetailResponse.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/response/OrderResponse.java
  service/order/order_server/src/main/resources/application-local.yml
  service/order/order_server/src/test/java/com/sparta/order/OrderApplicationTests.java
  settings.gradle
Labels: ✨ Feature

#18 [#14] 오더서버에 AuditorAware 기능 추가 및 필터 등록
  common/domain/src/main/java/com/sparta/commons/domain/exception/BusinessException.java
  common/domain/src/main/java/com/sparta/commons/domain/exception/ErrorCode.java
  service/order/order_server/build.gradle
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/configuration/AuditAwareImpl.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/configuration/AuthenticationImpl.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/configuration/JpaAuditConfig.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/configuration/SecurityConfig.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/SecurityContextFilter.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/exception/OrderErrorCode.java
Labels: ✨ Feature, 🔨 Refactor

#23 [#21] 배송 모듈 분리
  service/delivery/delivery_dto/.gitignore
  service/delivery/delivery_dto/build.gradle
  service/delivery/delivery_dto/src/main/java/com/sparta/delivery/dto/DeliveryDtoApplication.java
  service/delivery/delivery_dto/src/main/resources/application.properties
  service/delivery/delivery_dto/src/test/java/com/sparta/delivery_dto/DeliveryDtoApplicationTests.java
  service/delivery/delivery_server/.gitignore
  service/delivery/delivery_server/build.gradle
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/DeliveryServerApplication.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/domain/model/Delivery.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/domain/model/DeliveryRoute.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/domain/model/State.java
  service/delivery/delivery_server/src/main/resources/application-local.yml
  service/delivery/delivery_server/src/test/java/com/sparta/delivery_server/DeliveryServerApplicationTests.java
  service/order/order_dto/.gitignore
  service/order/order_dto/build.gradle
  service/order/order_dto/gradle/wrapper/gradle-wrapper.jar
  service/order/order_dto/gradle/wrapper/gradle-wrapper.properties
  service/order/order_dto/src/main/java/com/sparta/order/dto/OrderDtoApplication.java
  service/order/order_dto/src/main/resources/application.properties
  service/order/order_dto/src/test/java/com/sparta/order/dto/OrderDtoApplicationTests.java
  service/order/order_server/src/main/java/com/sparta/order/domain/model/Order.java
  service/order/order_server/src/main/java/com/sparta/order/domain/model/OrderState.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/response/OrderResponse.java
  settings.gradle
Labels: 🔨 Refactor

#24 [#20] Company 엔티티 정의 및 생성 api
  service/company/.gitignore
  service/company/build.gradle
  service/company/settings.gradle
  service/company/src/main/java/com/sparta/company/CompanyApplication.java
  service/company/src/main/java/com/sparta/company/application/dto/CompanyCreateRequest.java
  service/company/src/main/java/com/sparta/company/application/dto/CompanyResponse.java
  service/company/src/main/java/com/sparta/company/application/mapper/CompanyMapper.java
  service/company/src/main/java/com/sparta/company/application/service/CompanyService.java
  service/company/src/main/java/com/sparta/company/domain/Company.java
  service/company/src/main/java/com/sparta/company/domain/CompanyType.java
  service/company/src/main/java/com/sparta/company/exception/ErrorCode.java
  service/company/src/main/java/com/sparta/company/exception/GlobalExceptionHandler.java
  service/company/src/main/java/com/sparta/company/exception/HubNotFoundException.java
  service/company/src/main/java/com/sparta/company/infrastructure/client/HubClient.java
  service/company/src/main/java/com/sparta/company/infrastructure/repository/CompanyRepository.java
  service/company/src/main/java/com/sparta/company/presentation/controller/CompanyController.java
  service/company/src/main/resources/application.yml
  service/hub/hub-service/src/main/java/com/sparta/hub/application/dto/interhub/InterHubResponse.java
  service/hub/hub-service/src/main/java/com/sparta/hub/application/service/HubService.java
  service/hub/hub-service/src/main/java/com/sparta/hub/presentation/InternalHubController.java
Labels: ✨ Feature

#28 [#27] 업체 api 구현
  service/company/src/main/java/com/sparta/company/application/dto/CompanySearchCond.java
  service/company/src/main/java/com/sparta/company/application/dto/CompanyUpdateRequest.java
  service/company/src/main/java/com/sparta/company/application/mapper/CompanyMapper.java
  service/company/src/main/java/com/sparta/company/application/service/CompanyService.java
  service/company/src/main/java/com/sparta/company/domain/Company.java
  service/company/src/main/java/com/sparta/company/domain/CompanyType.java
  service/company/src/main/java/com/sparta/company/exception/AlreadyDeletedException.java
  service/company/src/main/java/com/sparta/company/exception/GlobalExceptionHandler.java
  service/company/src/main/java/com/sparta/company/infrastructure/repository/CompanyRepository.java
  service/company/src/main/java/com/sparta/company/infrastructure/repository/CompanyRepositoryCustom.java
  service/company/src/main/java/com/sparta/company/infrastructure/repository/CompanyRepositoryCustomImpl.java
  service/company/src/main/java/com/sparta/company/presentation/controller/CompanyController.java
  service/hub/hub-service/src/main/java/com/sparta/hub/application/dto/hub/HubCreateRequest.java
  service/hub/hub-service/src/main/java/com/sparta/hub/application/service/HubService.java
  service/hub/hub-service/src/main/java/com/sparta/hub/application/service/InterHubService.java
Labels: ✨ Feature

#30 [#22] 배송요청 API 구현
  service/delivery/delivery_dto/src/main/java/com/sparta/delivery/dto/StateUpdateDto.java
  service/delivery/delivery_server/build.gradle
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/DeliveryServerApplication.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/application/DeliveryFacadeService.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/application/DeliveryRouteService.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/application/DeliveryService.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/domain/model/Delivery.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/domain/model/DeliveryRoute.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/domain/model/State.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/client/HubClient.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/configuration/KafkaConfig.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/messaging/StateProducer.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/repository/DeliveryRepository.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/repository/DeliveryRouteRepository.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/presentation/DeliveryController.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/presentation/dto/DeliveryResponse.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/presentation/dto/DeliveryRouteResponse.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/presentation/exception/DeliveryErrorCode.java
  service/delivery/delivery_server/src/main/resources/application-local.yml
  service/hub/hub-service/src/main/java/com/sparta/hub/presentation/InterHubInternalController.java
  service/order/docker-compose.yml
  service/order/order_server/build.gradle
  service/order/order_server/src/main/java/com/sparta/order/domain/model/OrderState.java
  service/order/order_server/src/main/resources/application-local.yml
Labels: ✨ Feature

#37 [#32] 업체 배송 담당자에게 slack 알림을 보내는 스케줄러 개발
  service/notification/.gitignore
  service/notification/build.gradle
  service/notification/docker-compose.yml
  service/notification/src/main/java/com/sparta/notification/NotificationApplication.java
  service/notification/src/main/java/com/sparta/notification/application/scheduler/CompanyDeliveryAgentSlackNotificationScheduler.java
  service/notification/src/main/java/com/sparta/notification/application/scheduler/HubDeliveryAgentSlackNotificationScheduler.java
  service/notification/src/main/java/com/sparta/notification/application/service/SlackNotificationProvider.java
  service/notification/src/main/java/com/sparta/notification/application/utils/SlackNotificationSender.java
  service/notification/src/main/java/com/sparta/notification/application/utils/WeatherSummary.java
  service/notification/src/main/java/com/sparta/notification/domain/model/SlackNotification.java
  service/notification/src/main/java/com/sparta/notification/domain/repository/SlackNotificationImpl.java
  service/notification/src/main/java/com/sparta/notification/domain/repository/SlackNotificationRepository.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/configuration/SchedulerConfig.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/configuration/SlackConfig.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/configuration/TaskSchedulerConfig.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/configuration/properties/GeminiProperties.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/configuration/properties/SlackProperties.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/configuration/properties/WeatherProperties.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/feign/ai/GeminiFeignClient.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/feign/ai/GeminiFeignConfig.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/feign/ai/GenerateContentRequest.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/feign/ai/GenerateContentResponse.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/feign/delivery/DeliveryFeignClient.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/feign/user/UserFeignClient.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/feign/weather/WeatherDeserializer.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/feign/weather/WeatherFeignClient.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/feign/weather/WeatherFeignConfig.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/feign/weather/WeatherFeignDecoder.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/feign/weather/WeatherResponse.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/repository/SlackNotificationMongoRepository.java
  service/notification/src/main/java/com/sparta/notification/infrastructure/slack/SlackHelper.java
  service/notification/src/main/resources/application.yml
  service/notification/src/test/java/com/sparta/notification/NotificationApplicationTests.java
  service/user/user_server/src/main/java/com/sparta/user/application/service/shipping_manager/ShippingManagerInternalService.java
  service/user/user_server/src/main/java/com/sparta/user/domain/repository/shipping_manager/ShippingManagerRepository.java
  service/user/user_server/src/main/java/com/sparta/user/domain/repository/shipping_manager/ShippingManagerRepositoryImpl.java
  service/user/user_server/src/main/java/com/sparta/user/infrastructure/repository/shipping_manager/ShippingManagerJpaRepository.java
  service/user/user_server/src/main/java/com/sparta/user/presentation/controller/shipping_manager/ShippingManagerInternalController.java
  settings.gradle
Labels: ✨ Feature

#38 [#11] 주문생성 시 재고감소, 배달객체 생성을 Kafka로 처리
  common/domain/src/main/java/com/sparta/commons/domain/jpa/KafkaTopicConstant.java
  service/company/company_dto/src/main/java/com/sparta/company_dto/ProductDeductDto.java
  service/company/company_dto/src/main/resources/application.properties
  service/company/company_server/build.gradle
  service/company/company_server/src/main/java/com/sparta/company/application/service/ProductService.java
  service/company/company_server/src/main/java/com/sparta/company/domain/Product.java
  service/company/company_server/src/main/java/com/sparta/company/infrastructure/messaging/ProductDeductConsumer.java
  service/company/company_server/src/main/resources/application.yml
  service/delivery/delivery_dto/src/main/java/com/sparta/delivery/dto/DeliveryCreateDto.java
  service/delivery/delivery_dto/src/main/java/com/sparta/delivery/dto/DeliveryDto.java
  service/delivery/delivery_dto/src/main/java/com/sparta/delivery/dto/DeliveryRouteDto.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/application/DeliveryFacadeService.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/application/DeliveryService.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/client/CompanyClient.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/client/HubClient.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/messaging/DeliveryConsumer.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/repository/DeliveryRepository.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/presentation/exception/DeliveryErrorCode.java
  service/delivery/delivery_server/src/main/resources/application-local.yml
  service/gateway/gateway_server/src/main/resources/application.yml
  service/order/order_server/build.gradle
  service/order/order_server/src/main/java/com/sparta/order/application/service/OrderFacadeService.java
  service/order/order_server/src/main/java/com/sparta/order/application/service/OrderService.java
  service/order/order_server/src/main/java/com/sparta/order/domain/model/Order.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/configuration/KafkaConfig.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/messaging/DeliveryCreateErrorConsumer.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/messaging/DeliveryCreateProducer.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/messaging/ProductDeductErrorConsumer.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/messaging/ProductDeductProducer.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/repository/OrderRepository.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/controller/OrderController.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/exception/OrderErrorCode.java
  service/order/order_server/src/main/resources/application-local.yml
  service/user/user_server/src/main/resources/application.yml
Labels: ✨ Feature

#41 [#40] 주문/배송 내부 API 구현
  service/delivery/delivery_dto/src/main/java/com/sparta/delivery/dto/DeliveryRouteDto.java
  service/delivery/delivery_server/build.gradle
  service/delivery/delivery_server/src/main/generated/com/sparta/delivery/domain/model/QDelivery.java
  service/delivery/delivery_server/src/main/generated/com/sparta/delivery/domain/model/QDeliveryRoute.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/application/DeliveryFacadeService.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/application/DeliveryMapper.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/application/DeliveryService.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/domain/model/Delivery.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/domain/model/DeliveryRoute.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/configuration/JpaConfig.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/repository/DeliveryRepositoryCustom.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/repository/DeliveryRepositoryImpl.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/presentation/DeliveryInternalController.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/presentation/dto/DeliveryRouteResponse.java
  service/order/order_dto/src/main/java/com/sparta/order/dto/OrderDto.java
  service/order/order_server/src/main/java/com/sparta/order/application/service/OrderFacadeService.java
  service/order/order_server/src/main/java/com/sparta/order/application/service/OrderMapper.java
  service/order/order_server/src/main/java/com/sparta/order/application/service/OrderService.java
  service/order/order_server/src/main/java/com/sparta/order/domain/model/Order.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/repository/OrderRepository.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/controller/OrderInternalController.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/request/OrderCreateRequest.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/response/OrderResponse.java
Labels: ✨ Feature

#45 [#42] 주문, 배송에 조회 및 상태변경 API 구현
  common/domain/src/main/java/com/sparta/commons/domain/jpa/KafkaTopicConstant.java
  common/domain/src/main/java/com/sparta/commons/domain/jpa/UpdateStateRequest.java
  service/delivery/delivery_dto/src/test/java/com/sparta/delivery_dto/DeliveryDtoApplicationTests.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/application/DeliveryFacadeService.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/application/DeliveryService.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/domain/model/State.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/messaging/DeliveryConsumer.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/messaging/StateConsumer.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/messaging/StateProducer.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/presentation/DeliveryController.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/presentation/exception/DeliveryControllerAdvice.java
  service/order/order_server/src/main/java/com/sparta/order/application/service/OrderFacadeService.java
  service/order/order_server/src/main/java/com/sparta/order/application/service/OrderService.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/configuration/KafkaConfig.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/messaging/DeliveryCreateProducer.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/messaging/OrderSetDeliveryConsumer.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/messaging/StateProducer.java
  service/order/order_server/src/main/java/com/sparta/order/infrastructure/repository/OrderRepository.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/controller/OrderController.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/exception/OrderControllerAdvice.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/exception/OrderErrorCode.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/response/CompanyOrderResponse.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/response/OrderResponse.java
Labels: ✨ Feature

#39 [#36] 모니터링 / ai
  docker-compose.yml
  prometheus.yml
  service/company/company_server/build.gradle
  service/company/company_server/docker-compose.yml
  service/company/company_server/src/main/java/com/sparta/company/application/service/CompanyService.java
  service/company/company_server/src/main/java/com/sparta/company/application/service/ProductService.java
  service/company/company_server/src/main/java/com/sparta/company/domain/Company.java
  service/company/company_server/src/main/java/com/sparta/company/exception/CompanyErrorCode.java
  service/company/company_server/src/main/java/com/sparta/company/exception/HubErrorCode.java
  service/company/company_server/src/main/java/com/sparta/company/infrastructure/ai/GoogleAiService.java
  service/company/company_server/src/main/java/com/sparta/company/infrastructure/ai/config/RestTemplateConfig.java
  service/company/company_server/src/main/java/com/sparta/company/infrastructure/ai/dto/AiRequest.java
  service/company/company_server/src/main/java/com/sparta/company/infrastructure/ai/dto/AiResponse.java
  service/company/company_server/src/main/java/com/sparta/company/infrastructure/client/HubClient.java
  service/company/company_server/src/main/java/com/sparta/company/infrastructure/metrics/CounterConfiguration.java
  service/company/company_server/src/main/java/com/sparta/company/infrastructure/metrics/StockMetrics.java
  service/company/company_server/src/main/java/com/sparta/company/presentation/controller/company/CompanyController.java
  service/company/company_server/src/main/java/com/sparta/company/presentation/controller/company/CompanyInternalController.java
  service/company/company_server/src/main/java/com/sparta/company/presentation/controller/product/ProductController.java
  service/company/company_server/src/main/resources/application.yml
  service/eureka/build.gradle
  service/eureka/src/main/resources/application.yml
  service/gateway/gateway_server/src/main/resources/application.yml
  service/hub/hub-service/build.gradle
  service/hub/hub-service/docker-compose.yml
  service/hub/hub-service/src/main/java/com/sparta/hub/application/dto/interhub/InterHubUpdateRequest.java
  service/hub/hub-service/src/main/java/com/sparta/hub/application/service/HubInternalService.java
  service/hub/hub-service/src/main/java/com/sparta/hub/application/service/HubService.java
  service/hub/hub-service/src/main/java/com/sparta/hub/application/service/InterHubService.java
  service/hub/hub-service/src/main/java/com/sparta/hub/domain/Hub.java
  service/hub/hub-service/src/main/java/com/sparta/hub/domain/InterHub.java
  service/hub/hub-service/src/main/java/com/sparta/hub/exception/InterHubErrorCode.java
  service/hub/hub-service/src/main/java/com/sparta/hub/infrastructure/config/CacheConfig.java
  service/hub/hub-service/src/main/java/com/sparta/hub/infrastructure/config/swagger/SwaggerConfig.java
  service/hub/hub-service/src/main/java/com/sparta/hub/infrastructure/metircs/CounterConfiguration.java
  service/hub/hub-service/src/main/java/com/sparta/hub/presentation/InterHubController.java
  service/hub/hub-service/src/main/java/com/sparta/hub/presentation/InternalHubController.java
  service/hub/hub-service/src/main/resources/application.yml
  service/hub/hub_dto/src/main/java/com/sparta/hub/dto/InterHubStopResponse.java
Labels: ✨ Feature, 🔨 Refactor

#46 [#44] 주문/배송에 인가처리
  service/delivery/delivery_dto/src/main/java/com/sparta/delivery/dto/StateUpdateDto.java
  service/delivery/delivery_server/build.gradle
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/configuration/AuditAwareImpl.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/configuration/AuthenticationImpl.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/configuration/JpaConfig.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/configuration/KafkaConfig.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/configuration/SecurityConfig.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/infrastructure/messaging/StateProducer.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/presentation/SecurityContextFilter.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/presentation/controller/DeliveryController.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/presentation/controller/DeliveryInternalController.java
  service/delivery/delivery_server/src/main/java/com/sparta/delivery/presentation/exception/DeliveryErrorCode.java
  service/order/order_server/src/main/java/com/sparta/order/application/service/OrderFacadeService.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/controller/OrderController.java
  service/order/order_server/src/main/java/com/sparta/order/presentation/controller/OrderInternalController.java
Labels: ✨ Feature
